base: argparse and var_save() fix, to_array() optimization

diff --git a/cliinst-base b/cliinst-base
--- a/cliinst-base
+++ b/cliinst-base
@@ -9,8 +9,7 @@ which pkexec &>/dev/null && exec pkexec --disable-internal-agent "$0" "$@"
 ### TODO 0: Shall we merge this with the LiveKit Installer?
 ### TODO 1: DEDUP, always dedup, or case and switch would hang.
 ### NOTE 0: We assign gettext $"msgid" syntax to switch-cases where needed.
-TEXTDOMAIN="aosc-inst"
-TEXTDOMAINDIR="/usr/share/locale"
+export TEXTDOMAIN="aosc-inst" TEXTDOMAINDIR="/usr/share/locale"
 
 shopt -s checkwinsize # Refresh COLUMNS and LINES
 # Pre-escaped Formatting
@@ -40,11 +39,12 @@ learn_more(){ [ "$1" ] || return 1; declare -n ptr="MORE_$1"; indprint "$ptr"; }
 
 # var_save varname varval
 # Assuming no non-alphanumeric characters in $1
+# returns 1 if not u_conf or config writing failed.
 var_save(){
     [ "$2" ] || return 1
     # [ "$3" ] && set -- $1 $(keyval_conv "$2" "$3" "$4")
     export $1="$2"
-    [ $u_conf == y ] && echo -e "$(declare -p)\n" >> $config
+    [ $u_conf == y ] && declare -p "$1" >> "$config"
 }
 
 select_save(){ var_save "$@"; break; }
@@ -65,11 +65,9 @@ keyval_conv(){
 # to_array array_name ARRAY_SET
 # Crude and simple implementation using eval set.
 to_array(){
-    [ -z "$2" ] && return 1
-    local arr=$1
-    eval $arr='()'
-    eval set -- $2
-    for i; do eval "$arr+=('$i')"; done
+	[ "$1" ] || return 2
+	declare -n arr="$1"
+	shift; arr=("$@")
 }
 
 # opttoggle KEY [KEYS VALS]
@@ -112,23 +110,20 @@ $0 -h
 -m URL\tSets the mirror root URL." && exit 0
 
 : ${u_conf=y} ${config=/tmp/installation-config} ${mirror=http://mirrors.anthonos.org/anthon} ${target=/mnt/target}
-while getopts ":nc;t;m;" opt; do
+while getopts "nc:t:m:" opt; do
   case $opt in
     n)
         echo $"Not using a config file."
         u_conf=n;;
     c)
-        echo $"Setting config file to $2."
-        config="$2";;
+        echo $"Setting config file to $OPTARG."
+        config="$OPTARG";;
     t)
-        echo $"Setting mount target to $2."
-        target="$2";;
+        echo $"Setting mount target to $OPTARG."
+        target="$OPTARG";;
     m)
-        echo $"Setting mirror to $2."
-        mirror="$2";;
-    \?)
-        echo "Invalid option: -$OPTARG" >&2
-        ;;
+        echo $"Setting mirror to $OPTARG."
+        mirror="$OPTARG";;
   esac
 done
 export u_conf config mirror target
